# Update this when adding a new AndroidManifest.xml.
LOCAL_AAPT_FLAGS := \
	com.android.assets.product \
	com.android.assets.quantum \
	com.android.bubble \
	com.android.contacts.common \
	com.cipheros.dialer.about \
	com.cipheros.dialer.app \
	com.cipheros.dialer.app.manifests.activities \
	com.cipheros.dialer.assisteddialing \
	com.cipheros.dialer.assisteddialing.ui \
	com.cipheros.dialer.backup \
	com.cipheros.dialer.binary.aosp.testing \
	com.cipheros.dialer.binary.google \
	com.cipheros.dialer.blocking \
	com.cipheros.dialer.blockreportspam \
	com.cipheros.dialer.callcomposer \
	com.cipheros.dialer.callcomposer.camera \
	com.cipheros.dialer.callcomposer.camera.camerafocus \
	com.cipheros.dialer.callcomposer.cameraui \
	com.cipheros.dialer.calldetails \
	com.cipheros.dialer.calllog.config \
	com.cipheros.dialer.calllog.database \
	com.cipheros.dialer.calllog.ui \
	com.cipheros.dialer.calllog.ui.menu \
	com.cipheros.dialer.calllogutils \
	com.cipheros.dialer.clipboard \
	com.cipheros.dialer.commandline \
	com.cipheros.dialer.common \
	com.cipheros.dialer.common.concurrent.testing \
	com.cipheros.dialer.common.preference \
	com.cipheros.dialer.configprovider \
	com.cipheros.dialer.contacts.displaypreference \
	com.cipheros.dialer.contacts.resources \
	com.cipheros.dialer.contactphoto \
	com.cipheros.dialer.contactsfragment \
	com.cipheros.dialer.databasepopulator \
	com.cipheros.dialer.dialpadview \
	com.cipheros.dialer.dialpadview.theme \
	com.cipheros.dialer.enrichedcall.simulator \
	com.cipheros.dialer.feedback \
	com.cipheros.dialer.glidephotomanager.impl \
  com.cipheros.dialer.historyitemactions \
	com.cipheros.dialer.interactions \
	com.cipheros.dialer.lettertile \
	com.cipheros.dialer.location \
	com.cipheros.dialer.main.impl \
	com.cipheros.dialer.main.impl.toolbar \
	com.cipheros.dialer.main.impl.bottomnav \
	com.cipheros.dialer.notification \
	com.cipheros.dialer.oem \
	com.cipheros.dialer.phonelookup.database \
	com.cipheros.dialer.phonenumberutil \
	com.cipheros.dialer.postcall \
	com.cipheros.dialer.precall.impl \
	com.cipheros.dialer.precall.externalreceiver \
	com.cipheros.dialer.preferredsim.impl \
	com.cipheros.dialer.preferredsim.suggestion \
	com.cipheros.dialer.promotion.impl \
	com.cipheros.dialer.rtt \
	com.cipheros.dialer.searchfragment.common \
	com.cipheros.dialer.searchfragment.cp2 \
	com.cipheros.dialer.searchfragment.directories \
	com.cipheros.dialer.searchfragment.list \
	com.cipheros.dialer.searchfragment.nearbyplaces \
	com.cipheros.dialer.searchfragment.remote \
	com.cipheros.dialer.shortcuts \
	com.cipheros.dialer.simulator.impl \
	com.cipheros.dialer.simulator.service \
	com.cipheros.dialer.spam.promo \
	com.cipheros.dialer.speeddial \
	com.cipheros.dialer.spannable \
	com.cipheros.dialer.theme \
	com.cipheros.dialer.theme.base \
	com.cipheros.dialer.theme.base.impl \
	com.cipheros.dialer.theme.common \
	com.cipheros.dialer.theme.hidden \
	com.cipheros.dialer.util \
	com.cipheros.dialer.voicemail.listui \
	com.cipheros.dialer.voicemail.listui.error \
	com.cipheros.dialer.voicemail.listui.menu \
	com.cipheros.dialer.voicemail.settings \
	com.cipheros.dialer.voicemailstatus \
	com.cipheros.dialer.widget \
	com.android.incallui \
	com.android.incallui.answer.impl.affordance \
	com.android.incallui.answer.impl \
	com.android.incallui.answer.impl.answermethod \
	com.android.incallui.answer.impl.hint \
	com.android.incallui.audioroute \
	com.android.incallui.autoresizetext \
	com.android.incallui.calllocation.impl \
	com.android.incallui.callpending \
	com.android.incallui.commontheme \
	com.android.incallui.contactgrid \
	com.android.incallui.disconnectdialog \
	com.android.incallui.hold \
	com.android.incallui.incall.impl \
	com.android.incallui.rtt.impl \
	com.android.incallui.rtt.protocol \
  com.android.incallui.speakeasy \
	com.android.incallui.sessiondata \
	com.android.incallui.spam \
	com.android.incallui.speakerbuttonlogic \
	com.android.incallui.telecomeventui \
	com.android.incallui.video.impl \
	com.android.incallui.video.protocol \
	com.android.phoneapphelper \
	com.android.voicemail \
	com.android.voicemail.impl \
	com.android.voicemail.impl.configui \
